apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-hpa
  namespace: codeconnect-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service # Targets deployment in deployments/user-service-deployment.yaml
  minReplicas: 1        # Minimum pods allowed
  maxReplicas: 5        # Maximum pods allowed when traffic spikes
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 # Scales up when average CPU > 70%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80 # Scales up when average RAM > 80%
