apiVersion: v1
kind: Service
metadata:
  name: activemq-artemis
  namespace: codeconnect-dev
  labels:
    app: activemq-artemis
spec:
  type: ClusterIP
  ports:
    - name: stomp
      port: 61613
      targetPort: 61613
      protocol: TCP
    - name: core
      port: 61616
      targetPort: 61616
      protocol: TCP
    - name: web-console
      port: 8161
      targetPort: 8161
      protocol: TCP
  selector:
    app: activemq-artemis
