apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limit-range
  namespace: codeconnect-dev # Enforces default limits inside codeconnect-dev namespace
spec:
  limits:
    - default:
        cpu: 500m    # Fallback CPU limit if pod omits resources.limits.cpu
        memory: 512Mi # Fallback Memory limit if pod omits resources.limits.memory
      defaultRequest:
        cpu: 250m    # Fallback CPU request if pod omits resources.requests.cpu
        memory: 256Mi # Fallback Memory request if pod omits resources.requests.memory
      type: Container
