apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-resource-quota
  namespace: codeconnect-dev # Enforces budget inside codeconnect-dev namespace
spec:
  hard:
    requests.cpu: "2"    # Max 2 CPU cores requested across all dev pods
    requests.memory: 4Gi # Max 4GB RAM requested across all dev pods
    limits.cpu: "4"      # Absolute CPU ceiling limit across all dev pods
    limits.memory: 8Gi   # Absolute RAM ceiling limit across all dev pods
    pods: "20"           # Max 20 pods total allowed in dev namespace
