apiVersion: v1
kind: Service
metadata:
  name: redis # [SERVICE NAME / DNS HOSTNAME]: Creates redis:6379 (Referenced in gateway-configmap.yaml & user-service-configmap.yaml)
  namespace: codeconnect-dev
  labels:
    app: redis # [OBJECT LABEL]: Metadata label for grouping this Service object
spec:
  type: ClusterIP
  ports:
    - port: 6379       # [SERVICE PORT]: Exposed port inside cluster
      targetPort: 6379 # [TARGET PORT LINK]: Must match spec.containers.ports.containerPort in redis-statefulset.yaml
      name: redis
  selector:
    app: redis # [TRAFFIC ROUTER SELECTOR]: Must match spec.template.metadata.labels.app in redis-statefulset.yaml
