apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config # ConfigMap name; injected via configMapRef in gateway-deployment.yaml
  namespace: codeconnect-dev
  labels:
    app: gateway-service
data:
  SERVER_PORT: "8080"                         # Gateway port; maps to application.yml SERVER_PORT
  REDIS_HOST: "redis"                         # Maps to Service metadata.name: redis in redis-service.yaml
  REDIS_PORT: "6379"                          # Maps to Service port: 6379 in redis-service.yaml
  USER_SERVICE_URI: "http://user-service:8080" # Maps to Service metadata.name: user-service in user-service.yaml
