server:
  port: 8080

spring:
  application:
    name: gateway-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/codeconnect_db}
  session:
    store-type: redis
    redis:
      namespace: spring:session
  cloud:
    gateway:
      routes:
        - id: admin-service-route
          uri: ${USER_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/v1/admin/**
        - id: mentor-service-route
          uri: ${USER_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/v1/mentor/**
        - id: user-service-route
          uri: ${USER_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/v1/users/**
        - id: curriculum-service-route
          uri: ${CURRICULUM_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/api/v1/curriculum/**
        - id: submission-service-route
          uri: ${SUBMISSION_SERVICE_URI:http://localhost:8083}
          predicates:
            - Path=/api/v1/submissions/**
        - id: collab-service-route
          uri: ${COLLAB_SERVICE_URI:http://localhost:8084}
          predicates:
            - Path=/api/v1/collab/**, /ws-connect/**

codeconnect:
  gateway:
    user-service-uri: ${USER_SERVICE_URI:http://localhost:8081}
    curriculum-service-uri: ${CURRICULUM_SERVICE_URI:http://localhost:8082}
    submission-service-uri: ${SUBMISSION_SERVICE_URI:http://localhost:8083}
    collab-service-uri: ${COLLAB_SERVICE_URI:http://localhost:8084}
    error-base-uri: ${ERROR_BASE_URI:https://codeconnect.dev/errors}
  session:
    cookie-name: ${SESSION_COOKIE_NAME:APP_SESSION}
    cookie-secure: ${SESSION_COOKIE_SECURE:false}
    cookie-same-site: ${SESSION_COOKIE_SAME_SITE:Strict}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
