apiVersion: v1
kind: Service
metadata:
  name: collab-service
  namespace: codeconnect-dev
  labels:
    app: collab-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: collab-service
