apiVersion: v1
kind: Service
metadata:
  name: curriculum-service # [SERVICE NAME / DNS HOSTNAME]: Creates http://curriculum-service:8080 (Referenced in gateway-configmap.yaml)
  namespace: codeconnect-dev
  labels:
    app: curriculum-service # [OBJECT LABEL]: Metadata label for grouping this Service object
spec:
  type: ClusterIP
  ports:
    - port: 8080       # [SERVICE PORT]: Exposed port inside cluster
      targetPort: 8080 # [TARGET PORT LINK]: Must match spec.containers.ports.containerPort in curriculum-service-deployment.yaml
      name: http
  selector:
    app: curriculum-service # [TRAFFIC ROUTER SELECTOR]: Must match spec.template.metadata.labels.app in curriculum-service-deployment.yaml
