apiVersion: v1
kind: Service
metadata:
  name: gateway-service # [SERVICE NAME / DNS HOSTNAME]: Referenced in networking/ingress.yaml
  namespace: codeconnect-dev
  labels:
    app: gateway-service # [OBJECT LABEL]: Metadata label for grouping this Service object
spec:
  type: ClusterIP
  ports:
    - port: 8080       # [SERVICE PORT]: Exposed port inside cluster
      targetPort: 8080 # [TARGET PORT LINK]: Must match spec.containers.ports.containerPort in gateway-deployment.yaml
      name: http
  selector:
    app: gateway-service # [TRAFFIC ROUTER SELECTOR]: Must match spec.template.metadata.labels.app in gateway-deployment.yaml
