package com.codeconnect.user.infrastructure.security;

import com.codeconnect.user.infrastructure.config.InternalSecurityProperties;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.lang.NonNull;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.HexFormat;
import java.util.List;

/**
 * Filter enforcing Zero-Trust Tier 2 security for incoming microservice requests.
 * Validates HMAC signatures generated by the API Gateway and anti-replay timestamps.
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class InternalAuthenticationFilter extends OncePerRequestFilter {

    public static final String HEADER_USER_ID = "X-User-Id";
    public static final String HEADER_USER_ROLE = "X-User-Role";
    public static final String HEADER_USER_EMAIL = "X-User-Email";
    public static final String HEADER_TIMESTAMP = "X-Timestamp";
    public static final String HEADER_INTERNAL_SIGNATURE = "X-Internal-Signature";
    public static final String HEADER_CORRELATION_ID = "X-Correlation-ID";
    public static final String HEADER_SPAN_ID = "X-Span-Id";

    private final InternalSecurityProperties securityProperties;

    @Override
    protected void doFilterInternal(
        @NonNull HttpServletRequest request,
        @NonNull HttpServletResponse response,
        @NonNull FilterChain filterChain
    ) throws ServletException, IOException {

        String incomingCorrelationId = request.getHeader(HEADER_CORRELATION_ID);
        String correlationId = (incomingCorrelationId != null && !incomingCorrelationId.isBlank())
            ? incomingCorrelationId
            : "req-" + java.util.UUID.randomUUID().toString().substring(0, 8);

        String spanId = "span-user-" + java.util.UUID.randomUUID().toString().substring(0, 8);

        org.slf4j.MDC.put("traceId", correlationId);
        org.slf4j.MDC.put("spanId", spanId);

        response.setHeader(HEADER_CORRELATION_ID, correlationId);
        response.setHeader(HEADER_SPAN_ID, spanId);

        try {
            String path = request.getRequestURI();

            // Always permit unauthenticated health probes
            if (path.startsWith("/actuator/health")) {
                filterChain.doFilter(request, response);
                return;
            }

            String userId = request.getHeader(HEADER_USER_ID);
            String role = request.getHeader(HEADER_USER_ROLE);
            String email = request.getHeader(HEADER_USER_EMAIL);
            String timestampStr = request.getHeader(HEADER_TIMESTAMP);
            String signature = request.getHeader(HEADER_INTERNAL_SIGNATURE);

            if (timestampStr != null && signature != null) {
                try {
                    long timestamp = Long.parseLong(timestampStr);
                    long currentTimestamp = System.currentTimeMillis();
                    long maxSkewMs = securityProperties.maxClockSkewSeconds() * 1000L;

                    if (Math.abs(currentTimestamp - timestamp) > maxSkewMs) {
                        log.warn("Internal security verification failed: Clock skew exceeded for path {}", path);
                        response.sendError(HttpServletResponse.SC_FORBIDDEN, "Security verification failed: Stale request timestamp");
                        return;
                    }

                    String safeUserId = userId != null ? userId : "";
                    String safeRole = role != null ? role : "";
                    String safeEmail = email != null ? email : "";

                    String expectedSignature = calculateHmac(safeUserId, safeRole, safeEmail, timestampStr, securityProperties.internalSecret());
                    if (!expectedSignature.equalsIgnoreCase(signature)) {
                        log.warn("Internal security verification failed: HMAC signature mismatch for path {}", path);
                        response.sendError(HttpServletResponse.SC_FORBIDDEN, "Security verification failed: Invalid request signature");
                        return;
                    }

                    // Signature & Timestamp valid -> Populate SecurityContext
                    List<SimpleGrantedAuthority> authorities = safeRole.isBlank()
                        ? Collections.emptyList()
                        : List.of(new SimpleGrantedAuthority(safeRole.startsWith("ROLE_") ? safeRole : "ROLE_" + safeRole));

                    UsernamePasswordAuthenticationToken authentication =
                        new UsernamePasswordAuthenticationToken(safeUserId, safeEmail, authorities);

                    SecurityContextHolder.getContext().setAuthentication(authentication);

                } catch (NumberFormatException e) {
                    log.warn("Invalid timestamp header format for path {}", path);
                    response.sendError(HttpServletResponse.SC_FORBIDDEN, "Security verification failed: Invalid timestamp format");
                    return;
                }
            }

            filterChain.doFilter(request, response);
        } finally {
            org.slf4j.MDC.remove("traceId");
            org.slf4j.MDC.remove("spanId");
        }
    }

    private static String calculateHmac(String userId, String role, String email, String timestamp, String secret) {
        try {
            String payload = userId + ":" + role + ":" + email + ":" + timestamp;
            Mac mac = Mac.getInstance("HmacSHA256");
            SecretKeySpec keySpec = new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8), "HmacSHA256");
            mac.init(keySpec);
            byte[] rawHmac = mac.doFinal(payload.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(rawHmac);
        } catch (Exception e) {
            throw new IllegalStateException("Failed to calculate HMAC signature", e);
        }
    }
}
