apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: codeconnect
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  REDIS_HOST: "{{ .Release.Name }}-redis"
  REDIS_PORT: "6379"
  MONGODB_URI: "mongodb://{{ .Release.Name }}-mongodb:27017/{{ .Values.mongodb.database }}"
  USER_SERVICE_URI: "http://{{ .Release.Name }}-user-service:8081"
  GATEWAY_INTERNAL_URL: "http://{{ .Release.Name }}-gateway-service:8080"
