{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app.kubernetes.io/name: codeconnect
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-gateway-service
                port:
                  number: {{ .Values.gateway.service.port }}
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-gateway-service
                port:
                  number: {{ .Values.gateway.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
