apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-user-service
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.userService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: user-service
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-service
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: user-service
          image: "{{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}"
          imagePullPolicy: {{ .Values.userService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.userService.service.port }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MONGODB_URI
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: REDIS_HOST
            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: REDIS_PORT
          resources:
            {{- toYaml .Values.userService.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: {{ .Values.userService.probes.startup.path }}
              port: http
            failureThreshold: {{ .Values.userService.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.userService.probes.startup.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.userService.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.userService.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.userService.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.userService.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.userService.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.userService.probes.readiness.periodSeconds }}
